site_name: Aprendizaje Profundo
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  