site_name: Aprendizaje Profundo
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  